# Generated by Django 4.2.11 on 2024-07-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        
    ]

    operations = [
      
    ]
